# Generated by Django 6.0.7 on 2026-07-13 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=15)),
                ('purpose', models.CharField(choices=[('course_enrollment', 'Course Enrollment'), ('ebook_purchase', 'eBook Purchase'), ('membership', 'Membership Subscription'), ('chicks_order', 'Chicks Order'), ('consultancy', 'Consultancy Booking')], max_length=30)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('reference_model', models.CharField(blank=True, help_text='Model name of the related object', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
