# Generated by Django 6.0.7 on 2026-07-13 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('poultry', 'Poultry Consultancy'), ('piggery', 'Piggery Setup'), ('rabbit', 'Rabbit Farming'), ('goat', 'Goat & Sheep Farming'), ('dairy', 'Dairy Management'), ('vegetable', 'Vegetable Production'), ('business', 'Farm Business Planning'), ('biosecurity', 'Biosecurity Planning'), ('farm_visit', 'Farm Visits'), ('staff_training', 'Farm Staff Training')], max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 for quote-based', max_digits=10)),
                ('duration', models.CharField(blank=True, help_text='e.g. 2 hours, 1 day', max_length=50)),
                ('is_online', models.BooleanField(default=True, help_text='Available online')),
                ('is_in_person', models.BooleanField(default=True, help_text='Available in person')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Consultation Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('farm_visit', 'Farm Visit')], default='online', max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('phone', models.CharField(max_length=15)),
                ('farm_location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Describe your farming situation or question')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('consultant_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='consultancy.consultationservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
