# Generated by Django 6.0.7 on 2026-07-13 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('day_old', 'Day-old'), ('one_week', '1 Week'), ('two_weeks', '2 Weeks'), ('three_weeks', '3 Weeks'), ('one_month', '1 Month')], max_length=20)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('price_per_bird', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_code', models.CharField(blank=True, max_length=50)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['age', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChickType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kenbro', 'Kenbro'), ('sasso', 'Sasso'), ('sussex', 'Sussex')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chicks/types/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('delivery_address', models.TextField()),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('needs_brooding_guide', models.BooleanField(default=True)),
                ('needs_vaccination_schedule', models.BooleanField(default=True)),
                ('special_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Collection'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='chicks.chickbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chick_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chickbatch',
            name='chick_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='chicks.chicktype'),
        ),
        migrations.AlterUniqueTogether(
            name='chickbatch',
            unique_together={('chick_type', 'age', 'batch_code')},
        ),
    ]
